# Generated by Django 5.0 on 2023-12-26 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phoneNumber')),
                ('another_phone_number', models.CharField(max_length=11, verbose_name='anotherPhone_number')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('area', models.CharField(max_length=100, verbose_name='area')),
                ('zone', models.CharField(max_length=100, verbose_name='zone')),
                ('details_adress', models.TextField(verbose_name='detailsAdress')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='lastModified')),
            ],
            options={
                'verbose_name_plural': 'Shopping',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_item', models.AutoField(primary_key=True, serialize=False, verbose_name='orderItem')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='lastModified')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='productId')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userId')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False, verbose_name='carstId')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='castModified')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userId')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='orderItem')),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='All_Orders',
            fields=[
                ('all_orders_id', models.AutoField(primary_key=True, serialize=False, verbose_name='allOrdersId')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='lastModified')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='orders')),
            ],
            options={
                'verbose_name_plural': 'AllOrders',
            },
        ),
    ]
