# Generated by Django 5.0 on 2023-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_orders',
            name='all_orders_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='allOrdersId'),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='lastModified'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='carstId'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='castModified'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='lastModified'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_item',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='orderItem'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='another_phone_number',
            field=models.CharField(max_length=11, verbose_name='anotherPhone_number'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='details_adress',
            field=models.TextField(verbose_name='detailsAdress'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='lastModified'),
        ),
    ]
