# Generated by Django 5.0 on 2023-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='order_item',
        ),
        migrations.AddField(
            model_name='carts',
            name='order_item',
            field=models.ManyToManyField(to='orders.orders', verbose_name='orderItem'),
        ),
    ]
