# Generated by Django 5.0 on 2023-12-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('core', '0002_alter_customuser_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='category',
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='seller', to='category.category', verbose_name='category'),
        ),
    ]
