# Generated by Django 5.0 on 2023-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category_Name')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Category_Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last_Modified')),
            ],
        ),
    ]
