# Generated by Django 5.0 on 2023-12-18 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, max_length=1000, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Last_Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discount_Name')),
                ('discount_description', models.TextField(blank=True, null=True, verbose_name='Discount_Description')),
                ('discount_percent', models.IntegerField(blank=True, null=True, verbose_name='Discount')),
                ('discount_start', models.DateTimeField(verbose_name='Discount_start')),
                ('discount_end', models.DateTimeField(verbose_name='Discount_End')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('modified', models.DateTimeField(editable=False, verbose_name='Last_Modified')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category_Name')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Category_Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Last_Modified')),
                ('user', models.ManyToManyField(blank=True, related_name='category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product_Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product_Description')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Price')),
                ('ratting', models.FloatField(default=0, verbose_name='Ratting')),
                ('is_available', models.BooleanField(blank=True, default=True, null=True, verbose_name='Available_Status')),
                ('total_buyed', models.IntegerField(default=0, verbose_name='Total_Buyed')),
                ('delivery_is_free', models.BooleanField(default=False, verbose_name='Delivery_Status')),
                ('weight', models.FloatField(blank=True, default=0, null=True, verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('modified', models.DateTimeField(editable=False, verbose_name='Last_Modified')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.images', verbose_name='images')),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.offers', verbose_name='offers')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sellerId')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('modified', models.DateTimeField(editable=False, verbose_name='Last_Modified')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='products.reviews', verbose_name='reviews'),
        ),
    ]
