# Generated by Django 5.0 on 2023-12-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(editable=False, verbose_name='lastModified')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_title', models.CharField(max_length=100, verbose_name='productTitle')),
                ('description', models.TextField(verbose_name='productDescription')),
                ('price', models.FloatField(verbose_name='price')),
                ('ratting', models.FloatField(default=0, verbose_name='ratting')),
                ('is_available', models.BooleanField(default=True, verbose_name='availableStatus')),
                ('total_buyed', models.IntegerField(default=0, verbose_name='totalBuyed')),
                ('quantity', models.PositiveBigIntegerField()),
                ('delivery_is_free', models.BooleanField(default=False, verbose_name='deliveryStatus')),
                ('weight', models.FloatField(default=0, verbose_name='weight')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='slugField')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='lastModified')),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category', verbose_name='category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sellerId')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False, verbose_name='discountId')),
                ('discount_name', models.CharField(max_length=100, verbose_name='discountName')),
                ('discount_description', models.TextField(verbose_name='discountDescription')),
                ('discount_percent', models.IntegerField(verbose_name='discount')),
                ('discount_start', models.DateTimeField(verbose_name='discountStart')),
                ('discount_end', models.DateTimeField(verbose_name='discountEnd')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='lastModified')),
                ('active', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(max_length=1000, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='lastModified')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='reviewId')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='lastModified')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'unique_together': {('user', 'product_id')},
            },
        ),
    ]
