# Generated by Django 5.0 on 2023-12-18 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, max_length=100, verbose_name='slugField'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True, null=True, verbose_name='categoryDescription'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='categoryName'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='lastModified'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='images',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='lastModified'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_description',
            field=models.TextField(blank=True, null=True, verbose_name='discountDescription'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_end',
            field=models.DateTimeField(verbose_name='discountEnd'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='discountId'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='discountName'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_start',
            field=models.DateTimeField(verbose_name='discountStart'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='modified',
            field=models.DateTimeField(editable=False, verbose_name='lastModified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_is_free',
            field=models.BooleanField(default=False, verbose_name='deliveryStatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='productDescription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='availableStatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(editable=False, verbose_name='lastModified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='productName'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='productTitle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratting',
            field=models.FloatField(default=0, verbose_name='ratting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_buyed',
            field=models.IntegerField(default=0, verbose_name='totalBuyed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='modified',
            field=models.DateTimeField(editable=False, verbose_name='lastModified'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='reviewId'),
        ),
    ]
