# Generated by Django 5.0 on 2023-12-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='slugField'),
        ),
        migrations.AddField(
            model_name='offers',
            name='product',
            field=models.ManyToManyField(to='products.product', verbose_name='product'),
        ),
    ]
